// Code generated by gen.py; DO NOT EDIT.

package aot

import (
	"math"

	"github.com/shibukawa/pgmem/internal/aot/pgaot"
	"github.com/shibukawa/pgmem/internal/aot/pgaot/base"
)

var _ = math.Float64bits

// callExport dispatches a wasm export by name. ok is false for unknown names.
func callExport(m *base.Module, name string, a []uint64) (res []uint64, ok bool) {
	switch name {
	case "__wasm_call_ctors":
		if len(a) != 0 {
			panic("aot: __wasm_call_ctors: want 0 args")
		}
		pgaot.WasmCallCtors(m)
		return nil, true
	case "pq_buffer_remaining_data":
		if len(a) != 0 {
			panic("aot: pq_buffer_remaining_data: want 0 args")
		}
		r := pgaot.PqBufferRemainingData(m)
		return []uint64{uint64(uint32(r))}, true
	case "malloc":
		if len(a) != 1 {
			panic("aot: malloc: want 1 args")
		}
		r := pgaot.Malloc(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "free":
		if len(a) != 1 {
			panic("aot: free: want 1 args")
		}
		pgaot.Free(m, int32(uint32(a[0])))
		return nil, true
	case "ProcessStartupPacket":
		if len(a) != 3 {
			panic("aot: ProcessStartupPacket: want 3 args")
		}
		r := pgaot.ProcessStartupPacket(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_startPGlite":
		if len(a) != 0 {
			panic("aot: pgl_startPGlite: want 0 args")
		}
		pgaot.PglStartPGlite(m)
		return nil, true
	case "pgl_pq_flush":
		if len(a) != 0 {
			panic("aot: pgl_pq_flush: want 0 args")
		}
		pgaot.PglPqFlush(m)
		return nil, true
	case "pgl_getMyProcPort":
		if len(a) != 0 {
			panic("aot: pgl_getMyProcPort: want 0 args")
		}
		r := pgaot.PglGetMyProcPort(m)
		return []uint64{uint64(uint32(r))}, true
	case "pgl_sendConnData":
		if len(a) != 0 {
			panic("aot: pgl_sendConnData: want 0 args")
		}
		pgaot.PglSendConnData(m)
		return nil, true
	case "PostgresMainLongJmp":
		if len(a) != 0 {
			panic("aot: PostgresMainLongJmp: want 0 args")
		}
		pgaot.PostgresMainLongJmp(m)
		return nil, true
	case "PostgresMainLoopOnce":
		if len(a) != 0 {
			panic("aot: PostgresMainLoopOnce: want 0 args")
		}
		pgaot.PostgresMainLoopOnce(m)
		return nil, true
	case "PostgresSendReadyForQueryIfNecessary":
		if len(a) != 0 {
			panic("aot: PostgresSendReadyForQueryIfNecessary: want 0 args")
		}
		pgaot.PostgresSendReadyForQueryIfNecessary(m)
		return nil, true
	case "pgmem_reset_session":
		if len(a) != 1 {
			panic("aot: pgmem_reset_session: want 1 args")
		}
		pgaot.PgmemResetSession(m, int32(uint32(a[0])))
		return nil, true
	case "pgl_setPGliteExitStatus":
		if len(a) != 1 {
			panic("aot: pgl_setPGliteExitStatus: want 1 args")
		}
		r := pgaot.PglSetPGliteExitStatus(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_setPGliteActive":
		if len(a) != 1 {
			panic("aot: pgl_setPGliteActive: want 1 args")
		}
		r := pgaot.PglSetPGliteActive(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_run_atexit_funcs":
		if len(a) != 0 {
			panic("aot: pgl_run_atexit_funcs: want 0 args")
		}
		pgaot.PglRunAtexitFuncs(m)
		return nil, true
	case "pgl_freopen":
		if len(a) != 3 {
			panic("aot: pgl_freopen: want 3 args")
		}
		r := pgaot.PglFreopen(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgmem_init":
		if len(a) != 0 {
			panic("aot: pgmem_init: want 0 args")
		}
		pgaot.PgmemInit(m)
		return nil, true
	case "pgmem_main":
		if len(a) != 2 {
			panic("aot: pgmem_main: want 2 args")
		}
		r := pgaot.PgmemMain(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "pgmem_call_sighandler":
		if len(a) != 2 {
			panic("aot: pgmem_call_sighandler: want 2 args")
		}
		pgaot.PgmemCallSighandler(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "pgmem_module_name":
		if len(a) != 1 {
			panic("aot: pgmem_module_name: want 1 args")
		}
		r := pgaot.PgmemModuleName(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "emscripten_builtin_memalign":
		if len(a) != 2 {
			panic("aot: emscripten_builtin_memalign: want 2 args")
		}
		r := pgaot.EmscriptenBuiltinMemalign(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "_emscripten_timeout":
		if len(a) != 2 {
			panic("aot: _emscripten_timeout: want 2 args")
		}
		pgaot.EmscriptenTimeout(m, int32(uint32(a[0])), math.Float64frombits(a[1]))
		return nil, true
	case "_emscripten_stack_restore":
		if len(a) != 1 {
			panic("aot: _emscripten_stack_restore: want 1 args")
		}
		pgaot.EmscriptenStackRestore(m, int32(uint32(a[0])))
		return nil, true
	case "emscripten_stack_get_current":
		if len(a) != 0 {
			panic("aot: emscripten_stack_get_current: want 0 args")
		}
		r := pgaot.EmscriptenStackGetCurrent(m)
		return []uint64{uint64(uint32(r))}, true
	}
	return nil, false
}
