// Code generated by gen.py; DO NOT EDIT.

package aot

import (
	"math"

	"github.com/shibukawa/pgmem/internal/aot/pgaot"
	"github.com/shibukawa/pgmem/internal/aot/pgaot/base"
)

var _ = math.Float64bits

// callExport dispatches a wasm export by name. ok is false for unknown names.
func callExport(m *base.Module, name string, a []uint64) (res []uint64, ok bool) {
	switch name {
	case "__wasm_call_ctors":
		if len(a) != 0 {
			panic("aot: __wasm_call_ctors: want 0 args")
		}
		pgaot.WasmCallCtors(m)
		return nil, true
	case "__errno_location":
		if len(a) != 0 {
			panic("aot: __errno_location: want 0 args")
		}
		r := pgaot.ErrnoLocation(m)
		return []uint64{uint64(uint32(r))}, true
	case "IsTransactionBlock":
		if len(a) != 0 {
			panic("aot: IsTransactionBlock: want 0 args")
		}
		r := pgaot.IsTransactionBlock(m)
		return []uint64{uint64(uint32(r))}, true
	case "fflush":
		if len(a) != 1 {
			panic("aot: fflush: want 1 args")
		}
		r := pgaot.Fflush(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_system":
		if len(a) != 1 {
			panic("aot: pgl_system: want 1 args")
		}
		r := pgaot.PglSystem(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_geteuid":
		if len(a) != 0 {
			panic("aot: pgl_geteuid: want 0 args")
		}
		r := pgaot.PglGeteuid(m)
		return []uint64{uint64(uint32(r))}, true
	case "pgl_exit":
		if len(a) != 1 {
			panic("aot: pgl_exit: want 1 args")
		}
		pgaot.PglExit(m, int32(uint32(a[0])))
		return nil, true
	case "pgl_connect":
		if len(a) != 3 {
			panic("aot: pgl_connect: want 3 args")
		}
		r := pgaot.PglConnect(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_send":
		if len(a) != 4 {
			panic("aot: pgl_send: want 4 args")
		}
		r := pgaot.PglSend(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_recv":
		if len(a) != 4 {
			panic("aot: pgl_recv: want 4 args")
		}
		r := pgaot.PglRecv(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_getsockname":
		if len(a) != 3 {
			panic("aot: pgl_getsockname: want 3 args")
		}
		r := pgaot.PglGetsockname(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_setsockopt":
		if len(a) != 5 {
			panic("aot: pgl_setsockopt: want 5 args")
		}
		r := pgaot.PglSetsockopt(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])), int32(uint32(a[4])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_fcntl":
		if len(a) != 3 {
			panic("aot: pgl_fcntl: want 3 args")
		}
		r := pgaot.PglFcntl(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pq_buffer_remaining_data":
		if len(a) != 0 {
			panic("aot: pq_buffer_remaining_data: want 0 args")
		}
		r := pgaot.PqBufferRemainingData(m)
		return []uint64{uint64(uint32(r))}, true
	case "pgl_getsockopt":
		if len(a) != 5 {
			panic("aot: pgl_getsockopt: want 5 args")
		}
		r := pgaot.PglGetsockopt(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])), int32(uint32(a[4])))
		return []uint64{uint64(uint32(r))}, true
	case "__main_argc_argv":
		if len(a) != 2 {
			panic("aot: __main_argc_argv: want 2 args")
		}
		r := pgaot.MainArgcArgv(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_getuid":
		if len(a) != 0 {
			panic("aot: pgl_getuid: want 0 args")
		}
		r := pgaot.PglGetuid(m)
		return []uint64{uint64(uint32(r))}, true
	case "pgl_shmdt":
		if len(a) != 1 {
			panic("aot: pgl_shmdt: want 1 args")
		}
		r := pgaot.PglShmdt(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_shmctl":
		if len(a) != 3 {
			panic("aot: pgl_shmctl: want 3 args")
		}
		r := pgaot.PglShmctl(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_shmat":
		if len(a) != 3 {
			panic("aot: pgl_shmat: want 3 args")
		}
		r := pgaot.PglShmat(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_shmget":
		if len(a) != 3 {
			panic("aot: pgl_shmget: want 3 args")
		}
		r := pgaot.PglShmget(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_munmap":
		if len(a) != 2 {
			panic("aot: pgl_munmap: want 2 args")
		}
		r := pgaot.PglMunmap(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "malloc":
		if len(a) != 1 {
			panic("aot: malloc: want 1 args")
		}
		r := pgaot.Malloc(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "free":
		if len(a) != 1 {
			panic("aot: free: want 1 args")
		}
		pgaot.Free(m, int32(uint32(a[0])))
		return nil, true
	case "pgl_popen":
		if len(a) != 2 {
			panic("aot: pgl_popen: want 2 args")
		}
		r := pgaot.PglPopen(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_pclose":
		if len(a) != 1 {
			panic("aot: pgl_pclose: want 1 args")
		}
		r := pgaot.PglPclose(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_atexit":
		if len(a) != 1 {
			panic("aot: pgl_atexit: want 1 args")
		}
		r := pgaot.PglAtexit(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgmem_poll":
		if len(a) != 3 {
			panic("aot: pgmem_poll: want 3 args")
		}
		r := pgaot.PgmemPoll(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "ProcessStartupPacket":
		if len(a) != 3 {
			panic("aot: ProcessStartupPacket: want 3 args")
		}
		r := pgaot.ProcessStartupPacket(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "htons":
		if len(a) != 1 {
			panic("aot: htons: want 1 args")
		}
		r := pgaot.Htons(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "htonl":
		if len(a) != 1 {
			panic("aot: htonl: want 1 args")
		}
		r := pgaot.Htonl(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_startPGlite":
		if len(a) != 0 {
			panic("aot: pgl_startPGlite: want 0 args")
		}
		pgaot.PglStartPGlite(m)
		return nil, true
	case "pgl_pq_flush":
		if len(a) != 0 {
			panic("aot: pgl_pq_flush: want 0 args")
		}
		pgaot.PglPqFlush(m)
		return nil, true
	case "pgl_getMyProcPort":
		if len(a) != 0 {
			panic("aot: pgl_getMyProcPort: want 0 args")
		}
		r := pgaot.PglGetMyProcPort(m)
		return []uint64{uint64(uint32(r))}, true
	case "pgl_sendConnData":
		if len(a) != 0 {
			panic("aot: pgl_sendConnData: want 0 args")
		}
		pgaot.PglSendConnData(m)
		return nil, true
	case "PostgresMainLongJmp":
		if len(a) != 0 {
			panic("aot: PostgresMainLongJmp: want 0 args")
		}
		pgaot.PostgresMainLongJmp(m)
		return nil, true
	case "PostgresMainLoopOnce":
		if len(a) != 0 {
			panic("aot: PostgresMainLoopOnce: want 0 args")
		}
		pgaot.PostgresMainLoopOnce(m)
		return nil, true
	case "PostgresSendReadyForQueryIfNecessary":
		if len(a) != 0 {
			panic("aot: PostgresSendReadyForQueryIfNecessary: want 0 args")
		}
		pgaot.PostgresSendReadyForQueryIfNecessary(m)
		return nil, true
	case "pgl_setPGliteExitStatus":
		if len(a) != 1 {
			panic("aot: pgl_setPGliteExitStatus: want 1 args")
		}
		r := pgaot.PglSetPGliteExitStatus(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_longjmp":
		if len(a) != 2 {
			panic("aot: pgl_longjmp: want 2 args")
		}
		pgaot.PglLongjmp(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "pgl_getpwuid":
		if len(a) != 1 {
			panic("aot: pgl_getpwuid: want 1 args")
		}
		r := pgaot.PglGetpwuid(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "strerror":
		if len(a) != 1 {
			panic("aot: strerror: want 1 args")
		}
		r := pgaot.Strerror(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "clear_setitimer":
		if len(a) != 0 {
			panic("aot: clear_setitimer: want 0 args")
		}
		pgaot.ClearSetitimer(m)
		return nil, true
	case "pgl_setPGliteActive":
		if len(a) != 1 {
			panic("aot: pgl_setPGliteActive: want 1 args")
		}
		r := pgaot.PglSetPGliteActive(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_getPGliteExitStatus":
		if len(a) != 0 {
			panic("aot: pgl_getPGliteExitStatus: want 0 args")
		}
		r := pgaot.PglGetPGliteExitStatus(m)
		return []uint64{uint64(uint32(r))}, true
	case "pgl_siglongjmp":
		if len(a) != 2 {
			panic("aot: pgl_siglongjmp: want 2 args")
		}
		pgaot.PglSiglongjmp(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "pgl_set_system_fn":
		if len(a) != 1 {
			panic("aot: pgl_set_system_fn: want 1 args")
		}
		pgaot.PglSetSystemFn(m, int32(uint32(a[0])))
		return nil, true
	case "pgl_set_popen_fn":
		if len(a) != 1 {
			panic("aot: pgl_set_popen_fn: want 1 args")
		}
		pgaot.PglSetPopenFn(m, int32(uint32(a[0])))
		return nil, true
	case "pgl_set_pclose_fn":
		if len(a) != 1 {
			panic("aot: pgl_set_pclose_fn: want 1 args")
		}
		pgaot.PglSetPcloseFn(m, int32(uint32(a[0])))
		return nil, true
	case "pgl_run_atexit_funcs":
		if len(a) != 0 {
			panic("aot: pgl_run_atexit_funcs: want 0 args")
		}
		pgaot.PglRunAtexitFuncs(m)
		return nil, true
	case "pgl_freopen":
		if len(a) != 3 {
			panic("aot: pgl_freopen: want 3 args")
		}
		r := pgaot.PglFreopen(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgl_set_rw_cbs":
		if len(a) != 2 {
			panic("aot: pgl_set_rw_cbs: want 2 args")
		}
		pgaot.PglSetRwCbs(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "pgl_poll":
		if len(a) != 3 {
			panic("aot: pgl_poll: want 3 args")
		}
		r := pgaot.PglPoll(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "pgmem_init":
		if len(a) != 0 {
			panic("aot: pgmem_init: want 0 args")
		}
		pgaot.PgmemInit(m)
		return nil, true
	case "pgmem_main":
		if len(a) != 2 {
			panic("aot: pgmem_main: want 2 args")
		}
		r := pgaot.PgmemMain(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "pgmem_call_sighandler":
		if len(a) != 2 {
			panic("aot: pgmem_call_sighandler: want 2 args")
		}
		pgaot.PgmemCallSighandler(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "pgmem_module_name":
		if len(a) != 1 {
			panic("aot: pgmem_module_name: want 1 args")
		}
		r := pgaot.PgmemModuleName(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_plpgsql":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_plpgsql: want 0 args")
		}
		r := pgaot.PgMagicFuncPlpgsql(m)
		return []uint64{uint64(uint32(r))}, true
	case "_PG_init_plpgsql":
		if len(a) != 0 {
			panic("aot: _PG_init_plpgsql: want 0 args")
		}
		pgaot.PGInitPlpgsql(m)
		return nil, true
	case "pg_finfo_plpgsql_call_handler":
		if len(a) != 0 {
			panic("aot: pg_finfo_plpgsql_call_handler: want 0 args")
		}
		r := pgaot.PgFinfoPlpgsqlCallHandler(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_plpgsql_inline_handler":
		if len(a) != 0 {
			panic("aot: pg_finfo_plpgsql_inline_handler: want 0 args")
		}
		r := pgaot.PgFinfoPlpgsqlInlineHandler(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_plpgsql_validator":
		if len(a) != 0 {
			panic("aot: pg_finfo_plpgsql_validator: want 0 args")
		}
		r := pgaot.PgFinfoPlpgsqlValidator(m)
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_build_datatype":
		if len(a) != 4 {
			panic("aot: plpgsql_build_datatype: want 4 args")
		}
		r := pgaot.PlpgsqlBuildDatatype(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_call_handler":
		if len(a) != 1 {
			panic("aot: plpgsql_call_handler: want 1 args")
		}
		r := pgaot.PlpgsqlCallHandler(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_compile":
		if len(a) != 2 {
			panic("aot: plpgsql_compile: want 2 args")
		}
		r := pgaot.PlpgsqlCompile(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_exec_get_datum_type":
		if len(a) != 2 {
			panic("aot: plpgsql_exec_get_datum_type: want 2 args")
		}
		r := pgaot.PlpgsqlExecGetDatumType(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_inline_handler":
		if len(a) != 1 {
			panic("aot: plpgsql_inline_handler: want 1 args")
		}
		r := pgaot.PlpgsqlInlineHandler(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_ns_lookup":
		if len(a) != 6 {
			panic("aot: plpgsql_ns_lookup: want 6 args")
		}
		r := pgaot.PlpgsqlNsLookup(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])), int32(uint32(a[4])), int32(uint32(a[5])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_parser_setup":
		if len(a) != 2 {
			panic("aot: plpgsql_parser_setup: want 2 args")
		}
		pgaot.PlpgsqlParserSetup(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "plpgsql_recognize_err_condition":
		if len(a) != 2 {
			panic("aot: plpgsql_recognize_err_condition: want 2 args")
		}
		r := pgaot.PlpgsqlRecognizeErrCondition(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_stmt_typename":
		if len(a) != 1 {
			panic("aot: plpgsql_stmt_typename: want 1 args")
		}
		r := pgaot.PlpgsqlStmtTypename(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "plpgsql_validator":
		if len(a) != 1 {
			panic("aot: plpgsql_validator: want 1 args")
		}
		r := pgaot.PlpgsqlValidator(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_dict_snowball":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_dict_snowball: want 0 args")
		}
		r := pgaot.PgMagicFuncDictSnowball(m)
		return []uint64{uint64(uint32(r))}, true
	case "dsnowball_init":
		if len(a) != 1 {
			panic("aot: dsnowball_init: want 1 args")
		}
		r := pgaot.DsnowballInit(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "dsnowball_lexize":
		if len(a) != 1 {
			panic("aot: dsnowball_lexize: want 1 args")
		}
		r := pgaot.DsnowballLexize(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_dsnowball_init":
		if len(a) != 0 {
			panic("aot: pg_finfo_dsnowball_init: want 0 args")
		}
		r := pgaot.PgFinfoDsnowballInit(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_dsnowball_lexize":
		if len(a) != 0 {
			panic("aot: pg_finfo_dsnowball_lexize: want 0 args")
		}
		r := pgaot.PgFinfoDsnowballLexize(m)
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_cyrillic_and_mic":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_cyrillic_and_mic: want 0 args")
		}
		r := pgaot.PgMagicFuncCyrillicAndMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "iso_to_koi8r":
		if len(a) != 1 {
			panic("aot: iso_to_koi8r: want 1 args")
		}
		r := pgaot.IsoToKoi8r(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "iso_to_mic":
		if len(a) != 1 {
			panic("aot: iso_to_mic: want 1 args")
		}
		r := pgaot.IsoToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "iso_to_win1251":
		if len(a) != 1 {
			panic("aot: iso_to_win1251: want 1 args")
		}
		r := pgaot.IsoToWin1251(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "iso_to_win866":
		if len(a) != 1 {
			panic("aot: iso_to_win866: want 1 args")
		}
		r := pgaot.IsoToWin866(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "koi8r_to_iso":
		if len(a) != 1 {
			panic("aot: koi8r_to_iso: want 1 args")
		}
		r := pgaot.Koi8rToIso(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "koi8r_to_mic":
		if len(a) != 1 {
			panic("aot: koi8r_to_mic: want 1 args")
		}
		r := pgaot.Koi8rToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "koi8r_to_win1251":
		if len(a) != 1 {
			panic("aot: koi8r_to_win1251: want 1 args")
		}
		r := pgaot.Koi8rToWin1251(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "koi8r_to_win866":
		if len(a) != 1 {
			panic("aot: koi8r_to_win866: want 1 args")
		}
		r := pgaot.Koi8rToWin866(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_iso":
		if len(a) != 1 {
			panic("aot: mic_to_iso: want 1 args")
		}
		r := pgaot.MicToIso(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_koi8r":
		if len(a) != 1 {
			panic("aot: mic_to_koi8r: want 1 args")
		}
		r := pgaot.MicToKoi8r(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_win1251":
		if len(a) != 1 {
			panic("aot: mic_to_win1251: want 1 args")
		}
		r := pgaot.MicToWin1251(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_win866":
		if len(a) != 1 {
			panic("aot: mic_to_win866: want 1 args")
		}
		r := pgaot.MicToWin866(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_iso_to_koi8r":
		if len(a) != 0 {
			panic("aot: pg_finfo_iso_to_koi8r: want 0 args")
		}
		r := pgaot.PgFinfoIsoToKoi8r(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_iso_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_iso_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoIsoToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_iso_to_win1251":
		if len(a) != 0 {
			panic("aot: pg_finfo_iso_to_win1251: want 0 args")
		}
		r := pgaot.PgFinfoIsoToWin1251(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_iso_to_win866":
		if len(a) != 0 {
			panic("aot: pg_finfo_iso_to_win866: want 0 args")
		}
		r := pgaot.PgFinfoIsoToWin866(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_koi8r_to_iso":
		if len(a) != 0 {
			panic("aot: pg_finfo_koi8r_to_iso: want 0 args")
		}
		r := pgaot.PgFinfoKoi8rToIso(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_koi8r_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_koi8r_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoKoi8rToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_koi8r_to_win1251":
		if len(a) != 0 {
			panic("aot: pg_finfo_koi8r_to_win1251: want 0 args")
		}
		r := pgaot.PgFinfoKoi8rToWin1251(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_koi8r_to_win866":
		if len(a) != 0 {
			panic("aot: pg_finfo_koi8r_to_win866: want 0 args")
		}
		r := pgaot.PgFinfoKoi8rToWin866(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_iso":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_iso: want 0 args")
		}
		r := pgaot.PgFinfoMicToIso(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_koi8r":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_koi8r: want 0 args")
		}
		r := pgaot.PgFinfoMicToKoi8r(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_win1251":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_win1251: want 0 args")
		}
		r := pgaot.PgFinfoMicToWin1251(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_win866":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_win866: want 0 args")
		}
		r := pgaot.PgFinfoMicToWin866(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win1251_to_iso":
		if len(a) != 0 {
			panic("aot: pg_finfo_win1251_to_iso: want 0 args")
		}
		r := pgaot.PgFinfoWin1251ToIso(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win1251_to_koi8r":
		if len(a) != 0 {
			panic("aot: pg_finfo_win1251_to_koi8r: want 0 args")
		}
		r := pgaot.PgFinfoWin1251ToKoi8r(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win1251_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_win1251_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoWin1251ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win1251_to_win866":
		if len(a) != 0 {
			panic("aot: pg_finfo_win1251_to_win866: want 0 args")
		}
		r := pgaot.PgFinfoWin1251ToWin866(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win866_to_iso":
		if len(a) != 0 {
			panic("aot: pg_finfo_win866_to_iso: want 0 args")
		}
		r := pgaot.PgFinfoWin866ToIso(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win866_to_koi8r":
		if len(a) != 0 {
			panic("aot: pg_finfo_win866_to_koi8r: want 0 args")
		}
		r := pgaot.PgFinfoWin866ToKoi8r(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win866_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_win866_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoWin866ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win866_to_win1251":
		if len(a) != 0 {
			panic("aot: pg_finfo_win866_to_win1251: want 0 args")
		}
		r := pgaot.PgFinfoWin866ToWin1251(m)
		return []uint64{uint64(uint32(r))}, true
	case "win1251_to_iso":
		if len(a) != 1 {
			panic("aot: win1251_to_iso: want 1 args")
		}
		r := pgaot.Win1251ToIso(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win1251_to_koi8r":
		if len(a) != 1 {
			panic("aot: win1251_to_koi8r: want 1 args")
		}
		r := pgaot.Win1251ToKoi8r(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win1251_to_mic":
		if len(a) != 1 {
			panic("aot: win1251_to_mic: want 1 args")
		}
		r := pgaot.Win1251ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win1251_to_win866":
		if len(a) != 1 {
			panic("aot: win1251_to_win866: want 1 args")
		}
		r := pgaot.Win1251ToWin866(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win866_to_iso":
		if len(a) != 1 {
			panic("aot: win866_to_iso: want 1 args")
		}
		r := pgaot.Win866ToIso(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win866_to_koi8r":
		if len(a) != 1 {
			panic("aot: win866_to_koi8r: want 1 args")
		}
		r := pgaot.Win866ToKoi8r(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win866_to_mic":
		if len(a) != 1 {
			panic("aot: win866_to_mic: want 1 args")
		}
		r := pgaot.Win866ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win866_to_win1251":
		if len(a) != 1 {
			panic("aot: win866_to_win1251: want 1 args")
		}
		r := pgaot.Win866ToWin1251(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_euc_cn_and_mic":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_euc_cn_and_mic: want 0 args")
		}
		r := pgaot.PgMagicFuncEucCnAndMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_cn_to_mic":
		if len(a) != 1 {
			panic("aot: euc_cn_to_mic: want 1 args")
		}
		r := pgaot.EucCnToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_euc_cn":
		if len(a) != 1 {
			panic("aot: mic_to_euc_cn: want 1 args")
		}
		r := pgaot.MicToEucCn(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_cn_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_cn_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoEucCnToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_euc_cn":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_euc_cn: want 0 args")
		}
		r := pgaot.PgFinfoMicToEucCn(m)
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_euc_jp_and_sjis":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_euc_jp_and_sjis: want 0 args")
		}
		r := pgaot.PgMagicFuncEucJpAndSjis(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_jp_to_mic":
		if len(a) != 1 {
			panic("aot: euc_jp_to_mic: want 1 args")
		}
		r := pgaot.EucJpToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "euc_jp_to_sjis":
		if len(a) != 1 {
			panic("aot: euc_jp_to_sjis: want 1 args")
		}
		r := pgaot.EucJpToSjis(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_euc_jp":
		if len(a) != 1 {
			panic("aot: mic_to_euc_jp: want 1 args")
		}
		r := pgaot.MicToEucJp(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_sjis":
		if len(a) != 1 {
			panic("aot: mic_to_sjis: want 1 args")
		}
		r := pgaot.MicToSjis(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_jp_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_jp_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoEucJpToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_jp_to_sjis":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_jp_to_sjis: want 0 args")
		}
		r := pgaot.PgFinfoEucJpToSjis(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_euc_jp":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_euc_jp: want 0 args")
		}
		r := pgaot.PgFinfoMicToEucJp(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_sjis":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_sjis: want 0 args")
		}
		r := pgaot.PgFinfoMicToSjis(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_sjis_to_euc_jp":
		if len(a) != 0 {
			panic("aot: pg_finfo_sjis_to_euc_jp: want 0 args")
		}
		r := pgaot.PgFinfoSjisToEucJp(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_sjis_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_sjis_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoSjisToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "sjis_to_euc_jp":
		if len(a) != 1 {
			panic("aot: sjis_to_euc_jp: want 1 args")
		}
		r := pgaot.SjisToEucJp(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "sjis_to_mic":
		if len(a) != 1 {
			panic("aot: sjis_to_mic: want 1 args")
		}
		r := pgaot.SjisToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_euc_kr_and_mic":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_euc_kr_and_mic: want 0 args")
		}
		r := pgaot.PgMagicFuncEucKrAndMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_kr_to_mic":
		if len(a) != 1 {
			panic("aot: euc_kr_to_mic: want 1 args")
		}
		r := pgaot.EucKrToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_euc_kr":
		if len(a) != 1 {
			panic("aot: mic_to_euc_kr: want 1 args")
		}
		r := pgaot.MicToEucKr(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_kr_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_kr_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoEucKrToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_euc_kr":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_euc_kr: want 0 args")
		}
		r := pgaot.PgFinfoMicToEucKr(m)
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_euc_tw_and_big5":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_euc_tw_and_big5: want 0 args")
		}
		r := pgaot.PgMagicFuncEucTwAndBig5(m)
		return []uint64{uint64(uint32(r))}, true
	case "big5_to_euc_tw":
		if len(a) != 1 {
			panic("aot: big5_to_euc_tw: want 1 args")
		}
		r := pgaot.Big5ToEucTw(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "big5_to_mic":
		if len(a) != 1 {
			panic("aot: big5_to_mic: want 1 args")
		}
		r := pgaot.Big5ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "euc_tw_to_big5":
		if len(a) != 1 {
			panic("aot: euc_tw_to_big5: want 1 args")
		}
		r := pgaot.EucTwToBig5(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "euc_tw_to_mic":
		if len(a) != 1 {
			panic("aot: euc_tw_to_mic: want 1 args")
		}
		r := pgaot.EucTwToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_big5":
		if len(a) != 1 {
			panic("aot: mic_to_big5: want 1 args")
		}
		r := pgaot.MicToBig5(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_euc_tw":
		if len(a) != 1 {
			panic("aot: mic_to_euc_tw: want 1 args")
		}
		r := pgaot.MicToEucTw(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_big5_to_euc_tw":
		if len(a) != 0 {
			panic("aot: pg_finfo_big5_to_euc_tw: want 0 args")
		}
		r := pgaot.PgFinfoBig5ToEucTw(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_big5_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_big5_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoBig5ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_tw_to_big5":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_tw_to_big5: want 0 args")
		}
		r := pgaot.PgFinfoEucTwToBig5(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_tw_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_tw_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoEucTwToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_big5":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_big5: want 0 args")
		}
		r := pgaot.PgFinfoMicToBig5(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_euc_tw":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_euc_tw: want 0 args")
		}
		r := pgaot.PgFinfoMicToEucTw(m)
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_euc2004_sjis2004":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_euc2004_sjis2004: want 0 args")
		}
		r := pgaot.PgMagicFuncEuc2004Sjis2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_jis_2004_to_shift_jis_2004":
		if len(a) != 1 {
			panic("aot: euc_jis_2004_to_shift_jis_2004: want 1 args")
		}
		r := pgaot.EucJis_2004_toShiftJis_2004(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_jis_2004_to_shift_jis_2004":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_jis_2004_to_shift_jis_2004: want 0 args")
		}
		r := pgaot.PgFinfoEucJis_2004_toShiftJis_2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_shift_jis_2004_to_euc_jis_2004":
		if len(a) != 0 {
			panic("aot: pg_finfo_shift_jis_2004_to_euc_jis_2004: want 0 args")
		}
		r := pgaot.PgFinfoShiftJis_2004_toEucJis_2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "shift_jis_2004_to_euc_jis_2004":
		if len(a) != 1 {
			panic("aot: shift_jis_2004_to_euc_jis_2004: want 1 args")
		}
		r := pgaot.ShiftJis_2004_toEucJis_2004(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_latin_and_mic":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_latin_and_mic: want 0 args")
		}
		r := pgaot.PgMagicFuncLatinAndMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "latin1_to_mic":
		if len(a) != 1 {
			panic("aot: latin1_to_mic: want 1 args")
		}
		r := pgaot.Latin1ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "latin3_to_mic":
		if len(a) != 1 {
			panic("aot: latin3_to_mic: want 1 args")
		}
		r := pgaot.Latin3ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "latin4_to_mic":
		if len(a) != 1 {
			panic("aot: latin4_to_mic: want 1 args")
		}
		r := pgaot.Latin4ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_latin1":
		if len(a) != 1 {
			panic("aot: mic_to_latin1: want 1 args")
		}
		r := pgaot.MicToLatin1(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_latin3":
		if len(a) != 1 {
			panic("aot: mic_to_latin3: want 1 args")
		}
		r := pgaot.MicToLatin3(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_latin4":
		if len(a) != 1 {
			panic("aot: mic_to_latin4: want 1 args")
		}
		r := pgaot.MicToLatin4(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_latin1_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_latin1_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoLatin1ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_latin3_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_latin3_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoLatin3ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_latin4_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_latin4_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoLatin4ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_latin1":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_latin1: want 0 args")
		}
		r := pgaot.PgFinfoMicToLatin1(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_latin3":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_latin3: want 0 args")
		}
		r := pgaot.PgFinfoMicToLatin3(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_latin4":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_latin4: want 0 args")
		}
		r := pgaot.PgFinfoMicToLatin4(m)
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_latin2_and_win1250":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_latin2_and_win1250: want 0 args")
		}
		r := pgaot.PgMagicFuncLatin2AndWin1250(m)
		return []uint64{uint64(uint32(r))}, true
	case "latin2_to_mic":
		if len(a) != 1 {
			panic("aot: latin2_to_mic: want 1 args")
		}
		r := pgaot.Latin2ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "latin2_to_win1250":
		if len(a) != 1 {
			panic("aot: latin2_to_win1250: want 1 args")
		}
		r := pgaot.Latin2ToWin1250(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_latin2":
		if len(a) != 1 {
			panic("aot: mic_to_latin2: want 1 args")
		}
		r := pgaot.MicToLatin2(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "mic_to_win1250":
		if len(a) != 1 {
			panic("aot: mic_to_win1250: want 1 args")
		}
		r := pgaot.MicToWin1250(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_latin2_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_latin2_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoLatin2ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_latin2_to_win1250":
		if len(a) != 0 {
			panic("aot: pg_finfo_latin2_to_win1250: want 0 args")
		}
		r := pgaot.PgFinfoLatin2ToWin1250(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_latin2":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_latin2: want 0 args")
		}
		r := pgaot.PgFinfoMicToLatin2(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_mic_to_win1250":
		if len(a) != 0 {
			panic("aot: pg_finfo_mic_to_win1250: want 0 args")
		}
		r := pgaot.PgFinfoMicToWin1250(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win1250_to_latin2":
		if len(a) != 0 {
			panic("aot: pg_finfo_win1250_to_latin2: want 0 args")
		}
		r := pgaot.PgFinfoWin1250ToLatin2(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win1250_to_mic":
		if len(a) != 0 {
			panic("aot: pg_finfo_win1250_to_mic: want 0 args")
		}
		r := pgaot.PgFinfoWin1250ToMic(m)
		return []uint64{uint64(uint32(r))}, true
	case "win1250_to_latin2":
		if len(a) != 1 {
			panic("aot: win1250_to_latin2: want 1 args")
		}
		r := pgaot.Win1250ToLatin2(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win1250_to_mic":
		if len(a) != 1 {
			panic("aot: win1250_to_mic: want 1 args")
		}
		r := pgaot.Win1250ToMic(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_big5":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_big5: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndBig5(m)
		return []uint64{uint64(uint32(r))}, true
	case "big5_to_utf8":
		if len(a) != 1 {
			panic("aot: big5_to_utf8: want 1 args")
		}
		r := pgaot.Big5ToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_big5_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_big5_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoBig5ToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_big5":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_big5: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToBig5(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_big5":
		if len(a) != 1 {
			panic("aot: utf8_to_big5: want 1 args")
		}
		r := pgaot.Utf8ToBig5(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_cyrillic":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_cyrillic: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndCyrillic(m)
		return []uint64{uint64(uint32(r))}, true
	case "koi8r_to_utf8":
		if len(a) != 1 {
			panic("aot: koi8r_to_utf8: want 1 args")
		}
		r := pgaot.Koi8rToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "koi8u_to_utf8":
		if len(a) != 1 {
			panic("aot: koi8u_to_utf8: want 1 args")
		}
		r := pgaot.Koi8uToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_koi8r_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_koi8r_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoKoi8rToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_koi8u_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_koi8u_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoKoi8uToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_koi8r":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_koi8r: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToKoi8r(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_koi8u":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_koi8u: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToKoi8u(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_koi8r":
		if len(a) != 1 {
			panic("aot: utf8_to_koi8r: want 1 args")
		}
		r := pgaot.Utf8ToKoi8r(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_koi8u":
		if len(a) != 1 {
			panic("aot: utf8_to_koi8u: want 1 args")
		}
		r := pgaot.Utf8ToKoi8u(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_euc_cn":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_euc_cn: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndEucCn(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_cn_to_utf8":
		if len(a) != 1 {
			panic("aot: euc_cn_to_utf8: want 1 args")
		}
		r := pgaot.EucCnToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_cn_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_cn_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoEucCnToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_euc_cn":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_euc_cn: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToEucCn(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_euc_cn":
		if len(a) != 1 {
			panic("aot: utf8_to_euc_cn: want 1 args")
		}
		r := pgaot.Utf8ToEucCn(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_euc_jp":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_euc_jp: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndEucJp(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_jp_to_utf8":
		if len(a) != 1 {
			panic("aot: euc_jp_to_utf8: want 1 args")
		}
		r := pgaot.EucJpToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_jp_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_jp_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoEucJpToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_euc_jp":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_euc_jp: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToEucJp(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_euc_jp":
		if len(a) != 1 {
			panic("aot: utf8_to_euc_jp: want 1 args")
		}
		r := pgaot.Utf8ToEucJp(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_euc_kr":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_euc_kr: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndEucKr(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_kr_to_utf8":
		if len(a) != 1 {
			panic("aot: euc_kr_to_utf8: want 1 args")
		}
		r := pgaot.EucKrToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_kr_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_kr_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoEucKrToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_euc_kr":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_euc_kr: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToEucKr(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_euc_kr":
		if len(a) != 1 {
			panic("aot: utf8_to_euc_kr: want 1 args")
		}
		r := pgaot.Utf8ToEucKr(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_euc_tw":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_euc_tw: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndEucTw(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_tw_to_utf8":
		if len(a) != 1 {
			panic("aot: euc_tw_to_utf8: want 1 args")
		}
		r := pgaot.EucTwToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_tw_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_tw_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoEucTwToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_euc_tw":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_euc_tw: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToEucTw(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_euc_tw":
		if len(a) != 1 {
			panic("aot: utf8_to_euc_tw: want 1 args")
		}
		r := pgaot.Utf8ToEucTw(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_euc2004":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_euc2004: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndEuc2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "euc_jis_2004_to_utf8":
		if len(a) != 1 {
			panic("aot: euc_jis_2004_to_utf8: want 1 args")
		}
		r := pgaot.EucJis_2004_toUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_euc_jis_2004_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_euc_jis_2004_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoEucJis_2004_toUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_euc_jis_2004":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_euc_jis_2004: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToEucJis_2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_euc_jis_2004":
		if len(a) != 1 {
			panic("aot: utf8_to_euc_jis_2004: want 1 args")
		}
		r := pgaot.Utf8ToEucJis_2004(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_gb18030":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_gb18030: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndGb18030(m)
		return []uint64{uint64(uint32(r))}, true
	case "gb18030_to_utf8":
		if len(a) != 1 {
			panic("aot: gb18030_to_utf8: want 1 args")
		}
		r := pgaot.Gb18030ToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_gb18030_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_gb18030_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoGb18030ToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_gb18030":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_gb18030: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToGb18030(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_gb18030":
		if len(a) != 1 {
			panic("aot: utf8_to_gb18030: want 1 args")
		}
		r := pgaot.Utf8ToGb18030(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_gbk":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_gbk: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndGbk(m)
		return []uint64{uint64(uint32(r))}, true
	case "gbk_to_utf8":
		if len(a) != 1 {
			panic("aot: gbk_to_utf8: want 1 args")
		}
		r := pgaot.GbkToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_gbk_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_gbk_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoGbkToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_gbk":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_gbk: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToGbk(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_gbk":
		if len(a) != 1 {
			panic("aot: utf8_to_gbk: want 1 args")
		}
		r := pgaot.Utf8ToGbk(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_iso8859_1":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_iso8859_1: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndIso8859_1(m)
		return []uint64{uint64(uint32(r))}, true
	case "iso8859_1_to_utf8":
		if len(a) != 1 {
			panic("aot: iso8859_1_to_utf8: want 1 args")
		}
		r := pgaot.Iso8859_1_toUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_iso8859_1_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_iso8859_1_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoIso8859_1_toUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_iso8859_1":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_iso8859_1: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToIso8859_1(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_iso8859_1":
		if len(a) != 1 {
			panic("aot: utf8_to_iso8859_1: want 1 args")
		}
		r := pgaot.Utf8ToIso8859_1(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_iso8859":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_iso8859: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndIso8859(m)
		return []uint64{uint64(uint32(r))}, true
	case "iso8859_to_utf8":
		if len(a) != 1 {
			panic("aot: iso8859_to_utf8: want 1 args")
		}
		r := pgaot.Iso8859ToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_iso8859_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_iso8859_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoIso8859ToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_iso8859":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_iso8859: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToIso8859(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_iso8859":
		if len(a) != 1 {
			panic("aot: utf8_to_iso8859: want 1 args")
		}
		r := pgaot.Utf8ToIso8859(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_johab":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_johab: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndJohab(m)
		return []uint64{uint64(uint32(r))}, true
	case "johab_to_utf8":
		if len(a) != 1 {
			panic("aot: johab_to_utf8: want 1 args")
		}
		r := pgaot.JohabToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_johab_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_johab_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoJohabToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_johab":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_johab: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToJohab(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_johab":
		if len(a) != 1 {
			panic("aot: utf8_to_johab: want 1 args")
		}
		r := pgaot.Utf8ToJohab(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_sjis":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_sjis: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndSjis(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_sjis_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_sjis_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoSjisToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_sjis":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_sjis: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToSjis(m)
		return []uint64{uint64(uint32(r))}, true
	case "sjis_to_utf8":
		if len(a) != 1 {
			panic("aot: sjis_to_utf8: want 1 args")
		}
		r := pgaot.SjisToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_sjis":
		if len(a) != 1 {
			panic("aot: utf8_to_sjis: want 1 args")
		}
		r := pgaot.Utf8ToSjis(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_sjis2004":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_sjis2004: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndSjis2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_shift_jis_2004_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_shift_jis_2004_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoShiftJis_2004_toUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_shift_jis_2004":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_shift_jis_2004: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToShiftJis_2004(m)
		return []uint64{uint64(uint32(r))}, true
	case "shift_jis_2004_to_utf8":
		if len(a) != 1 {
			panic("aot: shift_jis_2004_to_utf8: want 1 args")
		}
		r := pgaot.ShiftJis_2004_toUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_shift_jis_2004":
		if len(a) != 1 {
			panic("aot: utf8_to_shift_jis_2004: want 1 args")
		}
		r := pgaot.Utf8ToShiftJis_2004(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_uhc":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_uhc: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndUhc(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_uhc_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_uhc_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoUhcToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_uhc":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_uhc: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToUhc(m)
		return []uint64{uint64(uint32(r))}, true
	case "uhc_to_utf8":
		if len(a) != 1 {
			panic("aot: uhc_to_utf8: want 1 args")
		}
		r := pgaot.UhcToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_uhc":
		if len(a) != 1 {
			panic("aot: utf8_to_uhc: want 1 args")
		}
		r := pgaot.Utf8ToUhc(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "Pg_magic_func_utf8_and_win":
		if len(a) != 0 {
			panic("aot: Pg_magic_func_utf8_and_win: want 0 args")
		}
		r := pgaot.PgMagicFuncUtf8AndWin(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_utf8_to_win":
		if len(a) != 0 {
			panic("aot: pg_finfo_utf8_to_win: want 0 args")
		}
		r := pgaot.PgFinfoUtf8ToWin(m)
		return []uint64{uint64(uint32(r))}, true
	case "pg_finfo_win_to_utf8":
		if len(a) != 0 {
			panic("aot: pg_finfo_win_to_utf8: want 0 args")
		}
		r := pgaot.PgFinfoWinToUtf8(m)
		return []uint64{uint64(uint32(r))}, true
	case "utf8_to_win":
		if len(a) != 1 {
			panic("aot: utf8_to_win: want 1 args")
		}
		r := pgaot.Utf8ToWin(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "win_to_utf8":
		if len(a) != 1 {
			panic("aot: win_to_utf8: want 1 args")
		}
		r := pgaot.WinToUtf8(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "_emscripten_memcpy_bulkmem":
		if len(a) != 3 {
			panic("aot: _emscripten_memcpy_bulkmem: want 3 args")
		}
		r := pgaot.EmscriptenMemcpyBulkmem(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "_emscripten_memset_bulkmem":
		if len(a) != 3 {
			panic("aot: _emscripten_memset_bulkmem: want 3 args")
		}
		r := pgaot.EmscriptenMemsetBulkmem(m, int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])))
		return []uint64{uint64(uint32(r))}, true
	case "__funcs_on_exit":
		if len(a) != 0 {
			panic("aot: __funcs_on_exit: want 0 args")
		}
		pgaot.FuncsOnExit(m)
		return nil, true
	case "emscripten_builtin_free":
		if len(a) != 1 {
			panic("aot: emscripten_builtin_free: want 1 args")
		}
		pgaot.EmscriptenBuiltinFree(m, int32(uint32(a[0])))
		return nil, true
	case "emscripten_builtin_memalign":
		if len(a) != 2 {
			panic("aot: emscripten_builtin_memalign: want 2 args")
		}
		r := pgaot.EmscriptenBuiltinMemalign(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "ntohs":
		if len(a) != 1 {
			panic("aot: ntohs: want 1 args")
		}
		r := pgaot.Ntohs(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "_emscripten_timeout":
		if len(a) != 2 {
			panic("aot: _emscripten_timeout: want 2 args")
		}
		pgaot.EmscriptenTimeout(m, int32(uint32(a[0])), math.Float64frombits(a[1]))
		return nil, true
	case "_emscripten_stack_restore":
		if len(a) != 1 {
			panic("aot: _emscripten_stack_restore: want 1 args")
		}
		pgaot.EmscriptenStackRestore(m, int32(uint32(a[0])))
		return nil, true
	case "_emscripten_stack_alloc":
		if len(a) != 1 {
			panic("aot: _emscripten_stack_alloc: want 1 args")
		}
		r := pgaot.EmscriptenStackAlloc(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "emscripten_stack_get_current":
		if len(a) != 0 {
			panic("aot: emscripten_stack_get_current: want 0 args")
		}
		r := pgaot.EmscriptenStackGetCurrent(m)
		return []uint64{uint64(uint32(r))}, true
	}
	return nil, false
}
