// Code generated by gen.py; DO NOT EDIT.

package aot

import (
	"math"

	"github.com/shibukawa/pgmem/internal/aot/pgaot/base"
)

var _ = math.Float64bits

var fn_env_pgmem_crc32c = mustLookup("env", "pgmem_crc32c")

func (a *imports) Pgmem_crc32c(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_crc32c.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_listen = mustLookup("env", "pgmem_listen")

func (a *imports) Pgmem_listen(m *base.Module, l0 int32, l1 int32) {
	fn_env_pgmem_listen.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})
}

var fn_env_getaddrinfo = mustLookup("env", "getaddrinfo")

func (a *imports) Getaddrinfo(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env_getaddrinfo.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env_emscripten_exit_with_live_runtime = mustLookup("env", "emscripten_exit_with_live_runtime")

func (a *imports) Emscripten_exit_with_live_runtime(m *base.Module) {
	fn_env_emscripten_exit_with_live_runtime.Call(a.h, a.mem, []uint64{})
}

var fn_env___assert_fail = mustLookup("env", "__assert_fail")

func (a *imports) X__assert_fail(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
	fn_env___assert_fail.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})
}

var fn_env_pgmem_random_bytes = mustLookup("env", "pgmem_random_bytes")

func (a *imports) Pgmem_random_bytes(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env_pgmem_random_bytes.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env_getnameinfo = mustLookup("env", "getnameinfo")

func (a *imports) Getnameinfo(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) int32 {
	return int32(uint32(fn_env_getnameinfo.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5)), uint64(uint32(l6))})))
}

var fn_env_pgmem_hash_create = mustLookup("env", "pgmem_hash_create")

func (a *imports) Pgmem_hash_create(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env_pgmem_hash_create.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env_pgmem_hash_reset = mustLookup("env", "pgmem_hash_reset")

func (a *imports) Pgmem_hash_reset(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env_pgmem_hash_reset.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env_pgmem_hash_update = mustLookup("env", "pgmem_hash_update")

func (a *imports) Pgmem_hash_update(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_hash_update.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_hash_final = mustLookup("env", "pgmem_hash_final")

func (a *imports) Pgmem_hash_final(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_hash_final.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_hash_free = mustLookup("env", "pgmem_hash_free")

func (a *imports) Pgmem_hash_free(m *base.Module, l0 int32) {
	fn_env_pgmem_hash_free.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})
}

var fn_env_exit = mustLookup("env", "exit")

func (a *imports) Exit(m *base.Module, l0 int32) {
	fn_env_exit.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})
}

var fn_env_pgmem_poll = mustLookup("env", "pgmem_poll")

func (a *imports) Pgmem_poll(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env_pgmem_poll.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env_pgmem_recv = mustLookup("env", "pgmem_recv")

func (a *imports) Pgmem_recv(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env_pgmem_recv.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env_pgmem_send = mustLookup("env", "pgmem_send")

func (a *imports) Pgmem_send(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env_pgmem_send.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env_pgmem_run = mustLookup("env", "pgmem_run")

func (a *imports) Pgmem_run(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_run.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_hash_info = mustLookup("env", "pgmem_hash_info")

func (a *imports) Pgmem_hash_info(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env_pgmem_hash_info.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env_pgmem_cipher_free = mustLookup("env", "pgmem_cipher_free")

func (a *imports) Pgmem_cipher_free(m *base.Module, l0 int32) {
	fn_env_pgmem_cipher_free.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})
}

var fn_env_pgmem_cipher_create = mustLookup("env", "pgmem_cipher_create")

func (a *imports) Pgmem_cipher_create(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env_pgmem_cipher_create.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env_pgmem_cipher_run = mustLookup("env", "pgmem_cipher_run")

func (a *imports) Pgmem_cipher_run(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) int32 {
	return int32(uint32(fn_env_pgmem_cipher_run.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5)), uint64(uint32(l6))})))
}

var fn_env_pgmem_deflate_create = mustLookup("env", "pgmem_deflate_create")

func (a *imports) Pgmem_deflate_create(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env_pgmem_deflate_create.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env_pgmem_deflate_write = mustLookup("env", "pgmem_deflate_write")

func (a *imports) Pgmem_deflate_write(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_deflate_write.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_zstream_read = mustLookup("env", "pgmem_zstream_read")

func (a *imports) Pgmem_zstream_read(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_zstream_read.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_deflate_finish = mustLookup("env", "pgmem_deflate_finish")

func (a *imports) Pgmem_deflate_finish(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env_pgmem_deflate_finish.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env_pgmem_zstream_free = mustLookup("env", "pgmem_zstream_free")

func (a *imports) Pgmem_zstream_free(m *base.Module, l0 int32) {
	fn_env_pgmem_zstream_free.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})
}

var fn_env_pgmem_inflate_all = mustLookup("env", "pgmem_inflate_all")

func (a *imports) Pgmem_inflate_all(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_inflate_all.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_bn_rand = mustLookup("env", "pgmem_bn_rand")

func (a *imports) Pgmem_bn_rand(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env_pgmem_bn_rand.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_pgmem_bn_op = mustLookup("env", "pgmem_bn_op")

func (a *imports) Pgmem_bn_op(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32) int32 {
	return int32(uint32(fn_env_pgmem_bn_op.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5)), uint64(uint32(l6)), uint64(uint32(l7)), uint64(uint32(l8))})))
}

var fn_wasi_snapshot_preview1_environ_sizes_get = mustLookup("wasi_snapshot_preview1", "environ_sizes_get")

func (a *imports) Environ_sizes_get(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_environ_sizes_get.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_wasi_snapshot_preview1_environ_get = mustLookup("wasi_snapshot_preview1", "environ_get")

func (a *imports) Environ_get(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_environ_get.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_wasi_snapshot_preview1_proc_exit = mustLookup("wasi_snapshot_preview1", "proc_exit")

func (a *imports) Proc_exit(m *base.Module, l0 int32) {
	fn_wasi_snapshot_preview1_proc_exit.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})
}

var fn_env__abort_js = mustLookup("env", "_abort_js")

func (a *imports) X_abort_js(m *base.Module) {
	fn_env__abort_js.Call(a.h, a.mem, []uint64{})
}

var fn_env___syscall_faccessat = mustLookup("env", "__syscall_faccessat")

func (a *imports) X__syscall_faccessat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_faccessat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_chdir = mustLookup("env", "__syscall_chdir")

func (a *imports) X__syscall_chdir(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env___syscall_chdir.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_chmod = mustLookup("env", "__syscall_chmod")

func (a *imports) X__syscall_chmod(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env___syscall_chmod.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env___syscall_fchownat = mustLookup("env", "__syscall_fchownat")

func (a *imports) X__syscall_fchownat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	return int32(uint32(fn_env___syscall_fchownat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4))})))
}

var fn_wasi_snapshot_preview1_clock_time_get = mustLookup("wasi_snapshot_preview1", "clock_time_get")

func (a *imports) Clock_time_get(m *base.Module, l0 int32, l1 int64, l2 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_clock_time_get.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(l1), uint64(uint32(l2))})))
}

var fn_wasi_snapshot_preview1_fd_close = mustLookup("wasi_snapshot_preview1", "fd_close")

func (a *imports) Fd_close(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_close.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_dup = mustLookup("env", "__syscall_dup")

func (a *imports) X__syscall_dup(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env___syscall_dup.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_dup3 = mustLookup("env", "__syscall_dup3")

func (a *imports) X__syscall_dup3(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_dup3.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env_emscripten_date_now = mustLookup("env", "emscripten_date_now")

func (a *imports) Emscripten_date_now(m *base.Module) float64 {
	return math.Float64frombits(fn_env_emscripten_date_now.Call(a.h, a.mem, []uint64{}))
}

var fn_env___syscall_fdatasync = mustLookup("env", "__syscall_fdatasync")

func (a *imports) X__syscall_fdatasync(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env___syscall_fdatasync.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_openat = mustLookup("env", "__syscall_openat")

func (a *imports) X__syscall_openat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_openat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_fcntl64 = mustLookup("env", "__syscall_fcntl64")

func (a *imports) X__syscall_fcntl64(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_fcntl64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env___syscall_ioctl = mustLookup("env", "__syscall_ioctl")

func (a *imports) X__syscall_ioctl(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_ioctl.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_wasi_snapshot_preview1_fd_write = mustLookup("wasi_snapshot_preview1", "fd_write")

func (a *imports) Fd_write(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_write.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_wasi_snapshot_preview1_fd_read = mustLookup("wasi_snapshot_preview1", "fd_read")

func (a *imports) Fd_read(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_read.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_fstat64 = mustLookup("env", "__syscall_fstat64")

func (a *imports) X__syscall_fstat64(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env___syscall_fstat64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env___syscall_stat64 = mustLookup("env", "__syscall_stat64")

func (a *imports) X__syscall_stat64(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env___syscall_stat64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env___syscall_newfstatat = mustLookup("env", "__syscall_newfstatat")

func (a *imports) X__syscall_newfstatat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_newfstatat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_lstat64 = mustLookup("env", "__syscall_lstat64")

func (a *imports) X__syscall_lstat64(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env___syscall_lstat64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_wasi_snapshot_preview1_fd_sync = mustLookup("wasi_snapshot_preview1", "fd_sync")

func (a *imports) Fd_sync(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_sync.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_ftruncate64 = mustLookup("env", "__syscall_ftruncate64")

func (a *imports) X__syscall_ftruncate64(m *base.Module, l0 int32, l1 int64) int32 {
	return int32(uint32(fn_env___syscall_ftruncate64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(l1)})))
}

var fn_env___syscall_getcwd = mustLookup("env", "__syscall_getcwd")

func (a *imports) X__syscall_getcwd(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_env___syscall_getcwd.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_wasi_snapshot_preview1_fd_fdstat_get = mustLookup("wasi_snapshot_preview1", "fd_fdstat_get")

func (a *imports) Fd_fdstat_get(m *base.Module, l0 int32, l1 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_fdstat_get.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})))
}

var fn_env_emscripten_get_now = mustLookup("env", "emscripten_get_now")

func (a *imports) Emscripten_get_now(m *base.Module) float64 {
	return math.Float64frombits(fn_env_emscripten_get_now.Call(a.h, a.mem, []uint64{}))
}

var fn_wasi_snapshot_preview1_fd_seek = mustLookup("wasi_snapshot_preview1", "fd_seek")

func (a *imports) Fd_seek(m *base.Module, l0 int32, l1 int64, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_seek.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(l1), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_mkdirat = mustLookup("env", "__syscall_mkdirat")

func (a *imports) X__syscall_mkdirat(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_mkdirat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env__tzset_js = mustLookup("env", "_tzset_js")

func (a *imports) X_tzset_js(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
	fn_env__tzset_js.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})
}

var fn_env__gmtime_js = mustLookup("env", "_gmtime_js")

func (a *imports) X_gmtime_js(m *base.Module, l0 int64, l1 int32) {
	fn_env__gmtime_js.Call(a.h, a.mem, []uint64{uint64(l0), uint64(uint32(l1))})
}

var fn_env__mmap_js = mustLookup("env", "_mmap_js")

func (a *imports) X_mmap_js(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int64, l5 int32, l6 int32) int32 {
	return int32(uint32(fn_env__mmap_js.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(l4), uint64(uint32(l5)), uint64(uint32(l6))})))
}

var fn_env___syscall_pipe = mustLookup("env", "__syscall_pipe")

func (a *imports) X__syscall_pipe(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env___syscall_pipe.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_fadvise64 = mustLookup("env", "__syscall_fadvise64")

func (a *imports) X__syscall_fadvise64(m *base.Module, l0 int32, l1 int64, l2 int64, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_fadvise64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(l1), uint64(l2), uint64(uint32(l3))})))
}

var fn_env___syscall_fallocate = mustLookup("env", "__syscall_fallocate")

func (a *imports) X__syscall_fallocate(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int64) int32 {
	return int32(uint32(fn_env___syscall_fallocate.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(l2), uint64(l3)})))
}

var fn_wasi_snapshot_preview1_fd_pread = mustLookup("wasi_snapshot_preview1", "fd_pread")

func (a *imports) Fd_pread(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_pread.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(l3), uint64(uint32(l4))})))
}

var fn_wasi_snapshot_preview1_fd_pwrite = mustLookup("wasi_snapshot_preview1", "fd_pwrite")

func (a *imports) Fd_pwrite(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32) int32 {
	return int32(uint32(fn_wasi_snapshot_preview1_fd_pwrite.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(l3), uint64(uint32(l4))})))
}

var fn_env__emscripten_runtime_keepalive_clear = mustLookup("env", "_emscripten_runtime_keepalive_clear")

func (a *imports) X_emscripten_runtime_keepalive_clear(m *base.Module) {
	fn_env__emscripten_runtime_keepalive_clear.Call(a.h, a.mem, []uint64{})
}

var fn_env___call_sighandler = mustLookup("env", "__call_sighandler")

func (a *imports) X__call_sighandler(m *base.Module, l0 int32, l1 int32) {
	fn_env___call_sighandler.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1))})
}

var fn_env___syscall_getdents64 = mustLookup("env", "__syscall_getdents64")

func (a *imports) X__syscall_getdents64(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_getdents64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env___syscall_readlinkat = mustLookup("env", "__syscall_readlinkat")

func (a *imports) X__syscall_readlinkat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_readlinkat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_renameat = mustLookup("env", "__syscall_renameat")

func (a *imports) X__syscall_renameat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_renameat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env___syscall_rmdir = mustLookup("env", "__syscall_rmdir")

func (a *imports) X__syscall_rmdir(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env___syscall_rmdir.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall__newselect = mustLookup("env", "__syscall__newselect")

func (a *imports) X__syscall__newselect(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	return int32(uint32(fn_env___syscall__newselect.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4))})))
}

var fn_env__setitimer_js = mustLookup("env", "_setitimer_js")

func (a *imports) X_setitimer_js(m *base.Module, l0 int32, l1 float64) int32 {
	return int32(uint32(fn_env__setitimer_js.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), math.Float64bits(l1)})))
}

var fn_env___syscall_symlinkat = mustLookup("env", "__syscall_symlinkat")

func (a *imports) X__syscall_symlinkat(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_symlinkat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env___syscall_truncate64 = mustLookup("env", "__syscall_truncate64")

func (a *imports) X__syscall_truncate64(m *base.Module, l0 int32, l1 int64) int32 {
	return int32(uint32(fn_env___syscall_truncate64.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(l1)})))
}

var fn_env___syscall_unlinkat = mustLookup("env", "__syscall_unlinkat")

func (a *imports) X__syscall_unlinkat(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return int32(uint32(fn_env___syscall_unlinkat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2))})))
}

var fn_env___syscall_utimensat = mustLookup("env", "__syscall_utimensat")

func (a *imports) X__syscall_utimensat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return int32(uint32(fn_env___syscall_utimensat.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3))})))
}

var fn_env_emscripten_resize_heap = mustLookup("env", "emscripten_resize_heap")

func (a *imports) Emscripten_resize_heap(m *base.Module, l0 int32) int32 {
	return int32(uint32(fn_env_emscripten_resize_heap.Call(a.h, a.mem, []uint64{uint64(uint32(l0))})))
}

var fn_env___syscall_accept4 = mustLookup("env", "__syscall_accept4")

func (a *imports) X__syscall_accept4(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_accept4.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env___syscall_bind = mustLookup("env", "__syscall_bind")

func (a *imports) X__syscall_bind(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_bind.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env___syscall_connect = mustLookup("env", "__syscall_connect")

func (a *imports) X__syscall_connect(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_connect.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env___syscall_listen = mustLookup("env", "__syscall_listen")

func (a *imports) X__syscall_listen(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_listen.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env___syscall_recvfrom = mustLookup("env", "__syscall_recvfrom")

func (a *imports) X__syscall_recvfrom(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_recvfrom.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env___syscall_sendto = mustLookup("env", "__syscall_sendto")

func (a *imports) X__syscall_sendto(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_sendto.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var fn_env___syscall_socket = mustLookup("env", "__syscall_socket")

func (a *imports) X__syscall_socket(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return int32(uint32(fn_env___syscall_socket.Call(a.h, a.mem, []uint64{uint64(uint32(l0)), uint64(uint32(l1)), uint64(uint32(l2)), uint64(uint32(l3)), uint64(uint32(l4)), uint64(uint32(l5))})))
}

var _ base.EnvImports = (*imports)(nil)
var _ base.Wasi_snapshot_preview1Imports = (*imports)(nil)
