#!/usr/bin/env python3
"""Generate the static module symbol table for pgmem_dl.c.

usage: gen_modules.py NM OUT.c NAME=obj.o[,obj.o...] ...
"""
import subprocess, sys, re

nm, out = sys.argv[1], sys.argv[2]
mods = []
for spec in sys.argv[3:]:
    name, objs = spec.split('=', 1)
    objs = [o for o in objs.split(',') if o]
    res = subprocess.run([nm, '--defined-only'] + objs, capture_output=True, text=True, check=True)
    syms = set()
    for line in res.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-2] == 'T':
            s = parts[-1]
            if re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', s):
                syms.add(s)
    mods.append((name, sorted(syms)))

with open(out, 'w') as f:
    f.write('/* generated by gen_modules.py; do not edit */\n')
    f.write('typedef struct pgmem_sym { const char *name; void *addr; } pgmem_sym;\n')
    f.write('typedef struct pgmem_module { const char *name; const pgmem_sym *syms; int nsyms; } pgmem_module;\n')
    for name, syms in mods:
        for s in syms:
            f.write(f'extern void {s}(void);\n')
        f.write(f'static const pgmem_sym syms_{name}[] = {{\n')
        for s in syms:
            f.write(f'  {{"{s}", (void *) {s}}},\n')
        f.write('};\n')
    f.write('const pgmem_module pgmem_modules[] = {\n')
    for name, syms in mods:
        f.write(f'  {{"{name}", syms_{name}, {len(syms)}}},\n')
    f.write('};\n')
    f.write(f'const int pgmem_nmodules = {len(mods)};\n')
print(f'generated {out}: ' + ', '.join(f'{n}({len(s)})' for n, s in mods))
