/*
 * pgmem_dl.c
 *   Static replacement for dlopen()/dlsym() used by dfmgr.c. Loadable
 *   modules (plpgsql, dict_snowball, encoding conversions) are linked into
 *   the main binary and registered in a table generated by gen_modules.py.
 */
#include <ctype.h>
#include <string.h>
#include <stdio.h>

typedef struct pgmem_sym
{
	const char *name;
	void	   *addr;
} pgmem_sym;

typedef struct pgmem_module
{
	const char *name;			/* library basename without suffix */
	const pgmem_sym *syms;
	int			nsyms;
} pgmem_module;

extern const pgmem_module pgmem_modules[];
extern const int pgmem_nmodules;

static char pgmem_dlerr[512];
static int	pgmem_dlerr_set = 0;

void *
pgmem_dlopen(const char *filename, int flags)
{
	const char *base;
	const char *dot;
	size_t		len;
	int			i;

	(void) flags;
	if (filename == NULL)
	{
		snprintf(pgmem_dlerr, sizeof(pgmem_dlerr), "dlopen(NULL) is not supported");
		pgmem_dlerr_set = 1;
		return NULL;
	}
	base = strrchr(filename, '/');
	base = base ? base + 1 : filename;
	dot = strrchr(base, '.');
	len = dot ? (size_t) (dot - base) : strlen(base);
	for (i = 0; i < pgmem_nmodules; i++)
	{
		if (strlen(pgmem_modules[i].name) == len &&
			strncmp(pgmem_modules[i].name, base, len) == 0)
			return (void *) &pgmem_modules[i];
	}
	snprintf(pgmem_dlerr, sizeof(pgmem_dlerr),
			 "%s: module is not linked into this pgmem build", filename);
	pgmem_dlerr_set = 1;
	return NULL;
}

void *
pgmem_dlsym(void *handle, const char *symbol)
{
	const pgmem_module *m = (const pgmem_module *) handle;
	char		buf[256];
	int			i;

	if (m == NULL || symbol == NULL)
		return NULL;
	/*
	 * Per-module renames applied at compile time (see build.sh): the
	 * suffix is the module name as a C identifier (uuid-ossp -> uuid_ossp).
	 */
	if (strcmp(symbol, "Pg_magic_func") == 0 || strcmp(symbol, "_PG_init") == 0)
	{
		size_t		n = strlen(symbol);
		const char *p;

		snprintf(buf, sizeof(buf), "%s_", symbol);
		n++;
		for (p = m->name; *p && n + 1 < sizeof(buf); p++, n++)
			buf[n] = (isalnum((unsigned char) *p) || *p == '_') ? *p : '_';
		buf[n] = '\0';
		symbol = buf;
	}
	for (i = 0; i < m->nsyms; i++)
	{
		if (strcmp(m->syms[i].name, symbol) == 0)
			return m->syms[i].addr;
	}
	snprintf(pgmem_dlerr, sizeof(pgmem_dlerr), "undefined symbol: %s", symbol);
	pgmem_dlerr_set = 1;
	return NULL;
}

int
pgmem_dlclose(void *handle)
{
	(void) handle;
	return 0;
}

char *
pgmem_dlerror(void)
{
	if (!pgmem_dlerr_set)
		return NULL;
	pgmem_dlerr_set = 0;
	return pgmem_dlerr;
}

/* List of module names, so the host can create placeholder .so files. */
const char *
pgmem_module_name(int i)
{
	if (i < 0 || i >= pgmem_nmodules)
		return NULL;
	return pgmem_modules[i].name;
}
